name: packit new

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      set_54x:
        description: "KERNEL: 5.4.x / none"
        required: false
        default: "none"
      set_510x:
        description: "KERNEL: 5.10.x / none"
        required: false
        default: "none"
      set_515x:
        description: "KERNEL: 5.15.x / none"
        required: false
        default: "none"
      set_60x:
        description: "KERNEL: 6.0.x / none"
        required: false
        default: "none"
      set_61x:
        description: "KERNEL: 6.1.x / none"
        required: false
        default: "none"
      set_ver:
        description: "VER: 22.12.1 / ..."
        required: false
        default: "22.12.1"

env:
  REPO_URL: https://github.com/unifreq/openwrt_packit
  REPO_BRANCH: master
  ROOTFS_URL: https://github.com/kissyouhunter/openwrt_N1/releases/download/rootfs/openwrt-armvirt-64-default-rootfs.tar.gz
  KERNEL_URL: https://github.com/kissyouhunter/kernel_N1/trunk/kernel
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  SERVERCHAN_SCKEY: true
  USE_CACHEWRTBUILD: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: telegrame_bot
      run: |
        cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c > CPU
        cat /proc/cpuinfo | grep "cpu cores" | uniq >> CPU
        sed -i 's|[[:space:]]||g; s|^.||' CPU && sed -i 's|CPU||g; s|pucores:||' CPU
        CPUNAME="$(awk 'NR==1' CPU)" && CPUCORES="$(awk 'NR==2' CPU)"
        rm -rf CPU
        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=🎉 主人：
          您正在使用kissyouhunter仓库 {CPU型号为 [ ${CPUNAME} ] 核心数 为 [ ${CPUCORES} ] 线程数为 [ $(nproc) ]的机器} 打包 ${{ github.event.inputs.set_54x }} ${{ github.event.inputs.set_510x }} ${{ github.event.inputs.set_515x }} ${{ github.event.inputs.set_60x }} ${{ github.event.inputs.set_61x }} 固件,请耐心等待...... 😋" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi

    - name: choose kernel
      run: |
        set_54x="${{ github.event.inputs.set_54x }}"
        if [ "$set_54x" = "none" ]; then
          echo "no kernel was chosen"
        else
          echo "KERNEL_5_4_Y=${set_54x}" >> $GITHUB_ENV
        fi

        set_510x="${{ github.event.inputs.set_510x }}"
        if [ "$set_510x" = "none" ]; then
          echo "no kernel was chosen"
        else
          echo "KERNEL_5_10_Y=${set_510x}" >> $GITHUB_ENV
        fi

        set_515x="${{ github.event.inputs.set_515x }}"
        if [ "$set_515x" = "none" ]; then
          echo "no kernel was chosen"
        else
          echo "KERNEL_5_15_Y=${set_515x}" >> $GITHUB_ENV
        fi

        set_60x="${{ github.event.inputs.set_60x }}"
        if [ "$set_60x" = "none" ]; then
          echo "no kernel was chosen"
        else
          echo "KERNEL_6_0_Y=${set_60x}" >> $GITHUB_ENV
        fi

        set_61x="${{ github.event.inputs.set_61x }}"
        if [ "$set_61x" = "none" ]; then
          echo "no kernel was chosen"
        else
          echo "KERNEL_6_1_Y=${set_61x}" >> $GITHUB_ENV
        fi

        set_ver="${{ github.event.inputs.set_ver }}"
        echo "OP_DATE=${set_ver}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@master
        
    - name: Installing requirements 
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo -E apt-get update
        sudo -E apt-get install subversion -y
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Download Openwrt_Packit
      id: packit
      run: |
        git clone $REPO_URL -b $REPO_BRANCH /tmp/packit
        sed -i 's|50000|25000|g' /tmp/packit/files/cpustat
        cd /tmp/packit
        curl -LO $ROOTFS_URL
        cp $GITHUB_WORKSPACE/mk_s905d_n1-docker.sh mk_s905d_n1-docker.sh -v
        cd /tmp/packit/files
        rm -f luci-admin-status-index-html-02.patch
        cp $GITHUB_WORKSPACE/luci-admin-status-index-html-02.patch luci-admin-status-index-html-02.patch -v
        rm -f amlogic_model_database.txt
        cp $GITHUB_WORKSPACE/amlogic_model_database.txt amlogic_model_database.txt -v
        rm -f openwrt-install-amlogic
        cp $GITHUB_WORKSPACE/openwrt-install-amlogic openwrt-install-amlogic -v

    - name: Pack OpenWrt
      id: pack
      run: |
        set_54x="${{ github.event.inputs.set_54x }}"
        if [ "$set_54x" = "none" ]; then
          echo "no kernel was chosen"
          echo "OP_54=none" >> $GITHUB_ENV
        else
          cd /tmp/packit
          rm -f make.env
          cp $GITHUB_WORKSPACE/make_kernel.env make.env -v
          sed -i 's|op-kissyouhunter|'"$KERNEL_5_4_Y"-kissyouhunter'|g' ./make.env
          sed -i 's|date|'"$OP_DATE"'|g' ./make.env
          svn co $KERNEL_URL/$KERNEL_5_4_Y
          mv $KERNEL_5_4_Y/* ./
          sudo bash mk_s905d_n1-docker.sh
          echo "OP_54=openwrt_s905d_n1_${OP_DATE}_${KERNEL_5_4_Y}-kissyouhunter.img.gz" >> $GITHUB_ENV
        fi

        set_510x="${{ github.event.inputs.set_510x }}"
        if [ "$set_510x" = "none" ]; then
          echo "no kernel was chosen"
          echo "OP_510=none" >> $GITHUB_ENV
        else
          cd /tmp/packit
          rm -f make.env
          cp $GITHUB_WORKSPACE/make_kernel.env make.env -v
          sed -i 's|op-kissyouhunter|'"$KERNEL_5_10_Y"-kissyouhunter'|g' ./make.env
          sed -i 's|date|'"$OP_DATE"'|g' ./make.env
          svn co $KERNEL_URL/$KERNEL_5_10_Y
          mv $KERNEL_5_10_Y/* ./
          sudo bash mk_s905d_n1-docker.sh
          echo "OP_510=openwrt_s905d_n1_${OP_DATE}_${KERNEL_5_10_Y}-kissyouhunter.img.gz" >> $GITHUB_ENV
        fi

        set_515x="${{ github.event.inputs.set_515x }}"
        if [ "$set_515x" = "none" ]; then
          echo "no kernel was chosen"
          echo "OP_515=none" >> $GITHUB_ENV
        else
          cd /tmp/packit
          rm -f make.env
          cp $GITHUB_WORKSPACE/make_kernel.env make.env -v
          sed -i 's|op-kissyouhunter|'"$KERNEL_5_15_Y"-kissyouhunter'|g' ./make.env
          sed -i 's|date|'"$OP_DATE"'|g' ./make.env
          svn co $KERNEL_URL/$KERNEL_5_15_Y
          mv $KERNEL_5_15_Y/* ./
          sudo bash mk_s905d_n1-docker.sh
          echo "OP_515=openwrt_s905d_n1_${OP_DATE}_${KERNEL_5_15_Y}-kissyouhunter.img.gz" >> $GITHUB_ENV
        fi

        set_60x="${{ github.event.inputs.set_60x }}"
        if [ "$set_60x" = "none" ]; then
          echo "no kernel was chosen"
          echo "OP_60=none" >> $GITHUB_ENV
        else
          cd /tmp/packit
          rm -f make.env
          cp $GITHUB_WORKSPACE/make_kernel.env make.env -v
          sed -i 's|op-kissyouhunter|'"$KERNEL_6_0_Y"-kissyouhunter'|g' ./make.env
          sed -i 's|date|'"$OP_DATE"'|g' ./make.env
          svn co $KERNEL_URL/$KERNEL_6_0_Y
          mv $KERNEL_6_0_Y/* ./
          sudo bash mk_s905d_n1-docker.sh
          echo "OP_60=openwrt_s905d_n1_${OP_DATE}_${KERNEL_6_0_Y}-kissyouhunter.img.gz" >> $GITHUB_ENV
        fi

        set_61x="${{ github.event.inputs.set_61x }}"
        if [ "$set_61x" = "none" ]; then
          echo "no kernel was chosen"
          echo "OP_61=none" >> $GITHUB_ENV
        else
          cd /tmp/packit
          rm -f make.env
          cp $GITHUB_WORKSPACE/make_kernel.env make.env -v
          sed -i 's|op-kissyouhunter|'"$KERNEL_6_1_Y"-kissyouhunter'|g' ./make.env
          sed -i 's|date|'"$OP_DATE"'|g' ./make.env
          svn co $KERNEL_URL/$KERNEL_6_1_Y
          mv $KERNEL_6_1_Y/* ./
          sudo bash mk_s905d_n1-docker.sh
          echo "OP_61=openwrt_s905d_n1_${OP_DATE}_${KERNEL_6_1_Y}-kissyouhunter.img.gz" >> $GITHUB_ENV
        fi

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd /tmp/packit/output
        sudo gzip -9 *
        sudo chmod 777 *
        ls -a
        ls -a /tmp/packit/output
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.OP_54 }}
        path: |
          ${{ env.FIRMWARE }}/${{ env.OP_54 }}

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.OP_510 }}
        path: |
          ${{ env.FIRMWARE }}/${{ env.OP_510 }}

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.OP_515 }}
        path: |
          ${{ env.FIRMWARE }}/${{ env.OP_515 }}

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.OP_60 }}
        path: |
          ${{ env.FIRMWARE }}/${{ env.OP_60 }}

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.OP_61 }}
        path: |
          ${{ env.FIRMWARE }}/${{ env.OP_61 }}

    #- name: Delete workflow runs
    #  uses: GitRML/delete-workflow-runs@main
    #  with:
    #    retain_days: 1
    #    keep_minimum_runs: 3

    - name: telegram_bot
      run: |
        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=我亲爱的✨主人✨：
          您使用kissyouhunter仓库打包的 ${{ github.event.inputs.set_54x }} ${{ github.event.inputs.set_510x }} ${{ github.event.inputs.set_515x }} ${{ github.event.inputs.set_60x }} ${{ github.event.inputs.set_61x }} 固件顺利完成了！💐" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi
